### ISSUE TITLE
Test - Data Engineering

### ISSUE THREAD

**Issue by VictorD-Bohorquez** [VictorD-Bohorquez/MLOps_Project#5]
Create the test files including class files if necesary to generate the test process and assertions for the validation of the data engineering process ( Data loading, data splitting and feature engineering).
The test files are suggested to be added at the folder path : src/testing

**Comment by hanszap** [comment]
Work in progress

**Comment by hanszap** [comment]
Closed as per pull request: https://github.com/VictorD-Bohorquez/MLOps_Project/pull/9
