### ISSUE TITLE
Test - Model Engineering

### ISSUE THREAD

**Issue by VictorD-Bohorquez** [VictorD-Bohorquez/MLOps_Project#6]
Create the test files including class files if necesary to generate the test process and assertions for the validation of the model engineering process ( Model training, model hyper parameters selection, model based accepted accuracy or other metrics).
The test files are suggested to be added at the folder path : src/testing

**Comment by RubenGTM** [comment]
2 tests have been executed successfully using framework pytest.
![evidencia_tests](https://github.com/user-attachments/assets/dc84f808-f517-496c-979c-363321206ebb)

**Comment by VictorD-Bohorquez** [comment]
@RubenGTM the issue is closed once the PR is merge into main, please review the comments and changes requested in your PR.
