### ISSUE TITLE
Test - Validate Models

### ISSUE THREAD

**Issue by VictorD-Bohorquez** [VictorD-Bohorquez/MLOps_Project#8]
Create the test files including class files if necesary to generate the test process and assertions for the validation of the trained model ( Expected accuracy, F1 score and other metrics). Also add some reports / graphs that shows the model performance. This testing should be done over Train and/or validation set only.
The test files are suggested to be added at the folder path : src/testing

**Comment by EnmaGalindo** [comment]
Changes were made using the PR created by MLOps_RubenGuerrero.
